export enum KeyReason {
  USER_REQUESTED = 'USER_REQUESTED',
  ACCOUNT_CLOSURE = 'ACCOUNT_CLOSURE',
  BRANCH_TRANSFER = 'BRANCH_TRANSFER',
  RECONCILIATION = 'RECONCILIATION',
  FRAUD = 'FRAUD',
  RFB_VALIDATION = 'RFB_VALIDATION',
}
